# Generated by Django 2.0.2 on 2019-05-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190504_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
