# Generated by Django 2.0.2 on 2019-05-05 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190504_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-created'], 'verbose_name': 'Servicios'},
        ),
    ]
